/sbin/mlnx-sf --action create --device 0000:03:00.0 --sfnum 2 --hwaddr 5c:25:73:79:c8:9c -t --cpu-list 0-2
/sbin/mlnx-sf --action create --device 0000:03:00.0 --sfnum 1514 --hwaddr 00:04:4b:44:cb:f0 -t --cpu-list 0-2
/sbin/mlnx-sf --action create --device 0000:03:00.0 --sfnum 3 --hwaddr 5c:25:73:79:c8:9d -t --cpu-list 0-2
/sbin/mlnx-sf --action create --device 0000:03:00.0 --sfnum 1515 --hwaddr 00:04:4b:9f:5f:f1 -t --cpu-list 0-2
