[hbn_profile]
profile_name = default

[BR_HBN_UPLINKS]
p0
p1

[BR_HBN_REPS]
pf0hpf
pf1hpf

[BR_HBN_SFS]


[BR_SFC_UPLINKS]


[BR_SFC_REPS]

[BR_SFC_SFS]


[BR_HBN_SFC_PATCH_PORTS]


[LINK_PROPAGATION]
p0:p0_if_r
p1:p1_if_r
pf0hpf:pf0hpf_if_r
pf1hpf:pf1hpf_if_r

[ENABLE_BR_SFC]


[ENABLE_BR_SFC_DEFAULT_FLOWS]


[ENABLE_VETH]


