BR_HBN_NAME=br-hbn
# Add mappings between the representor ports here.
# Format "bridge_for_portA~portA~portB~portA_hbn_dev~portA_of_port~portB_hbn_dev~portB_of_port"
# eg: 
# MAPPINGS=(
# "br-hbn~pf1hpf~pf1hpf_sf_r~pf1hpf_sf~pf1hpf_sf_r"
# "br-hbn~p1~p1_sf_r~p1_sf~p1_sf_r"
#)
# Below are generated mappings based on the number of SFs you provided
# on each ECPF to the install script. It also uses updated naming
# convention for representors
MAPPINGS=(
"br-hbn~p0~p0_if_r~p0_if~p0_if_r"
"br-hbn~p1~p1_if_r~p1_if~p1_if_r"
"br-hbn~pf0hpf~pf0hpf_if_r~pf0hpf_if~pf0hpf_if_r"
"br-hbn~pf1hpf~pf1hpf_if_r~pf1hpf_if~pf1hpf_if_r"
)
